### ISSUE TITLE
Log-in step occasionally fails.

### ISSUE THREAD

**Issue by stephenharris** [paulgibbs/behat-wordpress-extension#47] opened 2017-02-17 22:46 UTC
The "Given I am logged in as an <role>" test scenario occasionally fails on Travis-CI with a "The user could not be logged-in" error.

## Expected behavior
That the test passes all the time.

## Current behavior
The test fails occasionally. No pattern has been observed yet.

Known failing instances:

| Link                                                                                                                      | WP  | PHP | Driver |
|-------------------------------------------------------------------------------------------------------- | ------ | ------ | -------- |
| https://travis-ci.org/stephenharris/behat-wordpress-extension/jobs/202793337 | 4.7.2 | 5.6   | wpapi |
| https://travis-ci.org/paulgibbs/behat-wordpress-extension/jobs/205790372 | 4.7.2 | 5.6   | wpcli |
| https://travis-ci.org/paulgibbs/behat-wordpress-extension/jobs/205790376 | 4.7.2 | 7.1   | wpcli |
| https://travis-ci.org/paulgibbs/behat-wordpress-extension/jobs/206945238 | 4.7.2 | 7.1   | wpcli |

## Steps to reproduce (for bugs)

The failure happens occasionally. Let's use the above table to identify instances.

**Comment by stephenharris** [comment] 2017-02-17 22:49
This isn't new: https://github.com/stephenharris/WordPressBehatExtension/issues/10

The problem appears to be the same. I can't find the screenshot of an instance of this bug, but it too showed the password entered into the username field.

**Comment by stephenharris** [comment] 2017-03-20 11:56
Still happening occasionally. Here's a screenshot from my fork:

![user-8](https://cloud.githubusercontent.com/assets/3255034/24098801/4788c24a-0d64-11e7-8bac-5e9700d89af4.png)

**Comment by paulgibbs** [comment] 2017-03-21 11:44
This is pretty crazy.

**Comment by dealancer** [comment] 2018-02-07 16:40
Issue still exists for me when running tests locally or using Circle.CI.

**Comment by dealancer** [comment] 2018-02-07 18:49
I realized that the following exception is thrown in `loggedIn()`:

```
Unable to access the response content before visiting a page (Behat\Mink\Exception\DriverException)
```

**Comment by dealancer** [comment] 2018-02-07 19:03
It appears that I am getting log in error:
```
<div id="login_error">	<strong>ERROR</strong>: Invalid username. <a href="http://guwordpress.docksal/wp-login.php?action=lostpassword">Lost your password?</a><br></div>
```

**Comment by dealancer** [comment] 2018-02-07 19:21
There is definitely something wrong going on with `setValue()` method in `logIn()`. I called `getValue()` right after `setValue()` and it appears that the value is set improperly: a username is corrupted: `in` instead of `myadmin`, and empty string instead of a password.

**Comment by paulgibbs** [comment] 2018-02-07 23:32
I think there’s some bug in Selenium that causes this. There are reports of similar issues with Mink and Selenium across the web, but they’re infrequent and very hard to find. That whole stack is very complex and it looks so hard to debug I haven’t tried.

I think it’s safe to say until someone comes up with a reliable workaround or a fix, this is going to persist. The nearby calls to setFocus() were an attempt at this.

My lead theory is because the log-in step is usually the first thing done in a new web browser session, if Selenium sometimes tries to send commands to the browser before it is ready, it might cause this sort of failure. 

As I write this, I wonder about logIn() — if it fails, try to log-in twice, as a workaround. I wonder if it might have any impact. It would prove whether this sort of failure is unique to the *first* command in a session or not. (Because the second attempt would be the second command)

--- 
Paul Gibbs

**Comment by dealancer** [comment] 2018-02-08 01:07
Adding extra `setValue()` fixed the problem, but this issue seems really weird!

Here is my patch:

```
diff -ur behat-wordpress-extension/src/Context/Traits/UserAwareContextTrait.php behat-wordpress-extension-patched/src/Context/Traits/UserAwareContextTrait.php
--- behat-wordpress-extension/src/Context/Traits/UserAwareContextTrait.php      2018-02-07 18:27:56.000000000 -0500
+++ behat-wordpress-extension-patched/src/Context/Traits/UserAwareContextTrait.php      2018-02-07 18:27:48.000000000 -0500
@@ -39,6 +39,7 @@
         }
         $node->setValue('');
         $node->setValue($username);
+        $node->setValue($username);

         $node = $page->findField('user_pass');
         try {
@@ -48,6 +49,7 @@
         }
         $node->setValue('');
         $node->setValue($password);
+        $node->setValue($password);

         $page->findButton('wp-submit')->click();
```

**Comment by dealancer** [comment] 2018-02-08 03:57
@paulgibbs just saw your comment. I tried to alter all tests with a background condition to load homepage first, but that didn't affect on the log in errors. Hope it helps.

**Comment by paulgibbs** [comment] 2018-02-14 17:54
I've decided to merge it. I couldn't break it on Travis-CI, and I don't think it will hurt. I suspect whatever the very first step is, it might be occasionally prone to similar glitching, but without understanding the root cause more somehow, I've no better idea at the moment. :)

**Comment by paulgibbs** [comment] 2018-02-21 16:45
Unsurprisingly, the latest commit here does *not* fix this problem. It lives on!

**Comment by paulgibbs** [comment] 2018-03-20 22:50
Try https://stackoverflow.com/questions/26239561/behat-mink-selenium2-element-is-not-visible#26242599 next.

**Comment by dealancer** [comment] 2018-06-11 21:22
@paulgibbs it looks like this issue is still exists. It does not happen quite often, but for a large amount of tests, it happens nearly in 30% of builds.

**Comment by paulgibbs** [comment] 2018-06-11 23:49
Thanks for letting me know. What version are you testing with (or, what’s the the most recent version that causes this behaviour)?

--- 
Paul Gibbs

**Comment by paulgibbs** [comment] 2019-02-26 19:04
Latest attempted fix (with JS) and more information about the potential bug in Mink is detailed in #230.

**Comment by paulgibbs** [comment] 2019-05-15 15:32
https://github.com/Behat/MinkExtension/issues/286

**Comment by paulgibbs** [comment] 2019-05-31 14:05
Going to close this for now -- #247 is the latest stab. Will re-open if it is still not more reliable etc.

**Closed by paulgibbs** 2019-05-31 14:05 UTC
Labels: bug
